
#ifndef _GIMBLE_PRIMITIVETOPOLOGY_
#define _GIMBLE_PRIMITIVETOPOLOGY_

#include "GimbleReqs.h"

namespace Gimble
{
	namespace Graphics
	{
		enum PrimitiveTopology
	    {	
			PRIMITIVETOPOLOGY_UNDEFINED,
			PRIMITIVETOPOLOGY_POINTLIST,
			PRIMITIVETOPOLOGY_LINELIST,
			PRIMITIVETOPOLOGY_LINESTRIP,
			PRIMITIVETOPOLOGY_TRIANGLELIST,
			PRIMITIVETOPOLOGY_TRIANGLESTRIP,
			PRIMITIVETOPOLOGY_LINELIST_ADJ,
			PRIMITIVETOPOLOGY_LINESTRIP_ADJ,
			PRIMITIVETOPOLOGY_TRIANGLELIST_ADJ,
			PRIMITIVETOPOLOGY_TRIANGLESTRIP_ADJ
	    };
	}
}

#endif