
#ifndef _GIMBLE_PIXELFORMAT_
#define _GIMBLE_PIXELFORMAT_

#include "GimbleReqs.h"

namespace Gimble
{
	namespace Graphics
	{
		enum PixelFormat
		{
			PIXELFORMAT_UNKNOWN	                    = 0,
		    PIXELFORMAT_R32G32B32A32_TYPELESS       = 1,
		    PIXELFORMAT_R32G32B32A32_FLOAT          = 2,
		    PIXELFORMAT_R32G32B32A32_UINT           = 3,
		    PIXELFORMAT_R32G32B32A32_SINT           = 4,
		    PIXELFORMAT_R32G32B32_TYPELESS          = 5,
		    PIXELFORMAT_R32G32B32_FLOAT             = 6,
		    PIXELFORMAT_R32G32B32_UINT              = 7,
		    PIXELFORMAT_R32G32B32_SINT              = 8,
		    PIXELFORMAT_R16G16B16A16_TYPELESS       = 9,
		    PIXELFORMAT_R16G16B16A16_FLOAT          = 10,
		    PIXELFORMAT_R16G16B16A16_UNORM          = 11,
		    PIXELFORMAT_R16G16B16A16_UINT           = 12,
		    PIXELFORMAT_R16G16B16A16_SNORM          = 13,
		    PIXELFORMAT_R16G16B16A16_SINT           = 14,
		    PIXELFORMAT_R32G32_TYPELESS             = 15,
		    PIXELFORMAT_R32G32_FLOAT                = 16,
		    PIXELFORMAT_R32G32_UINT                 = 17,
		    PIXELFORMAT_R32G32_SINT                 = 18,
		    PIXELFORMAT_R32G8X24_TYPELESS           = 19,
		    PIXELFORMAT_D32_FLOAT_S8X24_UINT        = 20,
		    PIXELFORMAT_R32_FLOAT_X8X24_TYPELESS    = 21,
		    PIXELFORMAT_X32_TYPELESS_G8X24_UINT     = 22,
		    PIXELFORMAT_R10G10B10A2_TYPELESS        = 23,
		    PIXELFORMAT_R10G10B10A2_UNORM           = 24,
		    PIXELFORMAT_R10G10B10A2_UINT            = 25,
		    PIXELFORMAT_R11G11B10_FLOAT             = 26,
		    PIXELFORMAT_R8G8B8A8_TYPELESS           = 27,
		    PIXELFORMAT_R8G8B8A8_UNORM              = 28,
		    PIXELFORMAT_R8G8B8A8_UNORM_SRGB         = 29,
		    PIXELFORMAT_R8G8B8A8_UINT               = 30,
		    PIXELFORMAT_R8G8B8A8_SNORM              = 31,
		    PIXELFORMAT_R8G8B8A8_SINT               = 32,
		    PIXELFORMAT_R16G16_TYPELESS             = 33,
		    PIXELFORMAT_R16G16_FLOAT                = 34,
		    PIXELFORMAT_R16G16_UNORM                = 35,
		    PIXELFORMAT_R16G16_UINT                 = 36,
		    PIXELFORMAT_R16G16_SNORM                = 37,
		    PIXELFORMAT_R16G16_SINT                 = 38,
		    PIXELFORMAT_R32_TYPELESS                = 39,
		    PIXELFORMAT_D32_FLOAT                   = 40,
		    PIXELFORMAT_R32_FLOAT                   = 41,
		    PIXELFORMAT_R32_UINT                    = 42,
		    PIXELFORMAT_R32_SINT                    = 43,
		    PIXELFORMAT_R24G8_TYPELESS              = 44,
		    PIXELFORMAT_D24_UNORM_S8_UINT           = 45,
		    PIXELFORMAT_R24_UNORM_X8_TYPELESS       = 46,
		    PIXELFORMAT_X24_TYPELESS_G8_UINT        = 47,
		    PIXELFORMAT_R8G8_TYPELESS               = 48,
		    PIXELFORMAT_R8G8_UNORM                  = 49,
		    PIXELFORMAT_R8G8_UINT                   = 50,
		    PIXELFORMAT_R8G8_SNORM                  = 51,
		    PIXELFORMAT_R8G8_SINT                   = 52,
		    PIXELFORMAT_R16_TYPELESS                = 53,
		    PIXELFORMAT_R16_FLOAT                   = 54,
		    PIXELFORMAT_D16_UNORM                   = 55,
		    PIXELFORMAT_R16_UNORM                   = 56,
		    PIXELFORMAT_R16_UINT                    = 57,
		    PIXELFORMAT_R16_SNORM                   = 58,
		    PIXELFORMAT_R16_SINT                    = 59,
		    PIXELFORMAT_R8_TYPELESS                 = 60,
		    PIXELFORMAT_R8_UNORM                    = 61,
		    PIXELFORMAT_R8_UINT                     = 62,
		    PIXELFORMAT_R8_SNORM                    = 63,
		    PIXELFORMAT_R8_SINT                     = 64,
		    PIXELFORMAT_A8_UNORM                    = 65,
		    PIXELFORMAT_R1_UNORM                    = 66,
		    PIXELFORMAT_R9G9B9E5_SHAREDEXP          = 67,
		    PIXELFORMAT_R8G8_B8G8_UNORM             = 68,
		    PIXELFORMAT_G8R8_G8B8_UNORM             = 69,
		    PIXELFORMAT_BC1_TYPELESS                = 70,
		    PIXELFORMAT_BC1_UNORM                   = 71,
		    PIXELFORMAT_BC1_UNORM_SRGB              = 72,
		    PIXELFORMAT_BC2_TYPELESS                = 73,
		    PIXELFORMAT_BC2_UNORM                   = 74,
		    PIXELFORMAT_BC2_UNORM_SRGB              = 75,
		    PIXELFORMAT_BC3_TYPELESS                = 76,
		    PIXELFORMAT_BC3_UNORM                   = 77,
		    PIXELFORMAT_BC3_UNORM_SRGB              = 78,
		    PIXELFORMAT_BC4_TYPELESS                = 79,
		    PIXELFORMAT_BC4_UNORM                   = 80,
		    PIXELFORMAT_BC4_SNORM                   = 81,
		    PIXELFORMAT_BC5_TYPELESS                = 82,
		    PIXELFORMAT_BC5_UNORM                   = 83,
		    PIXELFORMAT_BC5_SNORM                   = 84,
		    PIXELFORMAT_B5G6R5_UNORM                = 85,
		    PIXELFORMAT_B5G5R5A1_UNORM              = 86,
		    PIXELFORMAT_B8G8R8A8_UNORM              = 87,
		    PIXELFORMAT_B8G8R8X8_UNORM              = 88,
		    PIXELFORMAT_R10G10B10_XR_BIAS_A2_UNORM  = 89,
		    PIXELFORMAT_B8G8R8A8_TYPELESS           = 90,
		    PIXELFORMAT_B8G8R8A8_UNORM_SRGB         = 91,
		    PIXELFORMAT_B8G8R8X8_TYPELESS           = 92,
		    PIXELFORMAT_B8G8R8X8_UNORM_SRGB         = 93,
		    PIXELFORMAT_BC6H_TYPELESS               = 94,
		    PIXELFORMAT_BC6H_UF16                   = 95,
		    PIXELFORMAT_BC6H_SF16                   = 96,
		    PIXELFORMAT_BC7_TYPELESS                = 97,
		    PIXELFORMAT_BC7_UNORM                   = 98,
		    PIXELFORMAT_BC7_UNORM_SRGB              = 99,
		    PIXELFORMAT_FORCE_UINT                  = 0xffffffff
		};
	};
}

#endif